#!/usr/bin/env python

import rospy
from std_msgs.msg import Int32 as Int32Msg
from dynamic_reconfigure.msg import Config as ConfigMsg
from dynamic_reconfigure.msg import BoolParameter as BoolParameterMsg
from dynamic_reconfigure.srv import Reconfigure as ReconfigureSrv
import subprocess

def callback(msg):
    if msg.data == 1:
        rospy.loginfo("Set ObjectLayer enabled")
        config = ConfigMsg(bools = [BoolParameterMsg("enabled", True)])

        global_costmap_srv = rospy.ServiceProxy("/move_base/global_costmap/object/set_parameters", ReconfigureSrv)
        local_costmap_srv = rospy.ServiceProxy("/move_base/local_costmap/object/set_parameters", ReconfigureSrv)
        try:
            # print(config)
            global_costmap_config = global_costmap_srv(config)
            local_costmap_config = local_costmap_srv(config)
        except:
            rospy.logerr("Failed to set ObjectLayer enabled")
    # else:
    #     print("ObjectLayer is disabled")

if __name__ == "__main__":
    rospy.init_node("costmap_updater")
    sub = rospy.Subscriber("/is_stuck", Int32Msg, callback)
    rospy.spin()
