#!/usr/bin/env python

import rospy
from safe_footstep_planner.msg import PolygonArray

mesh_msg = None

def callback(msg):
    global mesh_msg
    mesh_msg = msg

rospy.init_node("mesh_pub_booster")
sub = rospy.Subscriber("/original_meshed_polygons", PolygonArray, callback)
p = rospy.Publisher("/meshed_polygons", PolygonArray, queue_size=10)
r = rospy.Rate(100)

while not rospy.is_shutdown():
    if mesh_msg is not None:
        p.publish(mesh_msg)
    else:
        print("/meshed_polygon has not published yet")
    r.sleep()
