#!/usr/bin/env python
# from __future__ import print_function

import sys
import os
import rospy
import rospkg
import json
import time
import numpy as np
from safe_footstep_planner.srv import *
from safe_footstep_planner.msg import TargetFoothold
from std_srvs.srv import Empty
from geometry_msgs.msg import Point

import random # for test to set label randomly

class safe_footstep_operator:

  def __init__(self):
    self.sub_target_foothold = rospy.Subscriber("/footstep_planner/target_foothold", TargetFoothold, self.targetFootholdCallback)
    self.target_foothold = None
    print ('safe footstep operator initialized')

  def getDatabase(self):
    rospack = rospkg.RosPack()
    path = os.path.join(rospack.get_path('safe_footstep_planner'), 'config/database.json')
    fr = open(path, 'r')
    database = json.load(fr)
    # database = dict([(0,0), (1, 1), (2, 2), (3, 20), (4,10)])
    return database

  def saveDatabase(self, database):
    rospack = rospkg.RosPack()
    path = os.path.join(rospack.get_path('safe_footstep_planner'), 'config/database.json')
    fw = open(path, 'w')
    json.dump(database, fw)

  def checkFootholdClient(self, target_point, leg):
    rospy.wait_for_service('check_foothold')
    try:
      check_foothold = rospy.ServiceProxy('check_foothold', CheckFoothold)
      res = check_foothold(target_point, leg)
      return res.force_z
    except rospy.ServiceException, e:
      print "[check foothold] Service call failed: %s"%e

  # def targetFootholdServer(self, req):
  #   try:
  #     self.req = req
  #   except rospy.ServiceException, e:
  #     print "[target foothold] Service call failed: %s"%e
  #   return Empty()

  def targetFootholdCallback(self, data):
    self.target_foothold = data

  def startOperation(self):
    print('Press "y" to start foothold check.')
    start = raw_input('>>> ')
    if (start == 'y'):
      while (True):
        if (self.target_foothold):
          print('Press "s" to show target foothold.')
          print('Press "e" to execute check foothold.')
          print('Press "f" to finish operation.')
          key = raw_input('>>> ')
          if (key == 's'):
            print('Leg : %d' %self.target_foothold.leg)
            print('Target Foothold : (%s %s %s)' %(self.target_foothold.target.x, self.target_foothold.target.y, self.target_foothold.target.z))
          elif (key == 'e'):
            self.executeCheckFoothold()
          elif (key == 'f'):
            break
        else:
          print('Operation node has not received target foothold topic')
          time.sleep(1)
    else:
      print('Operation finished.')

  def executeCheckFoothold(self):
    label = str(self.target_foothold.label)
    leg = self.target_foothold.leg

    # for test without TargetFoothold
    # msg = Point()
    # msg.x = 0.25
    # msg.y = 0.00
    # msg.z = 0.07
    # label = str(random.randrange(4, 256))

    # modify target
    if (self.target_foothold.target.x < 0.0):
      self.target_foothold.target.x = 0.0
    if (self.target_foothold.target.x > 0.3):
      self.target_foothold.target.x = 0.3
    if (self.target_foothold.target.y < -0.1):
      self.target_foothold.target.y = -0.1
    if (self.target_foothold.target.y > 0.1):
      self.target_foothold.target.y = 0.1
    if (self.target_foothold.target.z < 0.0):
      self.target_foothold.target.z = 0.0
    if (self.target_foothold.target.z > 0.08):
      self.target_foothold.target.z = 0.08

    # wait for operator input
    print('Leg : %d' %self.target_foothold.leg)
    print('Target Foothold : (%s %s %s)' %(self.target_foothold.target.x, self.target_foothold.target.y, self.target_foothold.target.z))
    print('Press "y" to start foothold check.')
    start = raw_input('>>> ')
    if (start == 'y'):
      print('Foothold Checking...')
      force_z = self.checkFootholdClient(self.target_foothold.target, self.target_foothold.leg)
      # force_z = self.checkFootholdClient(msg)
    else:
      print('Foothold check Canceled.')

    # set cost
    force_offset = 50 # should be modified
    force_threshold = 100 # should be modified
    if (abs(force_z - force_offset) > force_threshold):
      cost = 2
    else:
      cost = 9

    # add data to database
    database = self.getDatabase()
    data = {label: cost}
    print("label: %s  cost: %d" %(label, cost))
    database.update(data)
    self.saveDatabase(database)
    print('Database Updated')

def main(args):
  rospy.init_node('safe_footstep_operator', anonymous=True)
  operator = safe_footstep_operator()
  try:
    # s = rospy.Service('target_foothold', GetTargetFoothold, operator.targetFootholdServer)
    operator.startOperation()
    rospy.spin()
  except KeyboardInterrupt:
    print("Shutting down")

if __name__ == '__main__':
    main(sys.argv)
